import { SchemaAST, FieldDefinition } from './ast.js';

function mapTsType(type: string): string {
  switch (type) {
    case 'string':
      return 'string';
    case 'int32':
    case 'uint32':
    case 'float':
    case 'double':
      return 'number';
    case 'int64':
      return 'bigint';
    case 'bool':
      return 'boolean';
    case 'bytes':
      return 'Uint8Array';
    default:
      return type; // nested message
  }
}

function generateWriterCall(field: FieldDefinition, accessor: string): string {
  switch (field.type) {
    case 'string':
      return `w.writeString(${accessor});`;
    case 'int32':
      return `w.writeInt32(${accessor});`;
    case 'uint32':
      return `w.writeUint32(${accessor});`;
    case 'float':
      return `w.writeFloat32(${accessor});`;
    case 'double':
      return `w.writeFloat64(${accessor});`;
    case 'int64':
      return `w.writeBigInt64(${accessor});`;
    case 'bool':
      return `w.writeBoolean(${accessor});`;
    case 'bytes':
      return `w.writeBytes(${accessor});`;
    default:
      return `w.writeBytes(encode${field.type}(${accessor}));`;
  }
}

function generateReaderCall(field: FieldDefinition): string {
  switch (field.type) {
    case 'string':
      return `r.readString()`;
    case 'int32':
      return `r.readInt32()`;
    case 'uint32':
      return `r.readUint32()`;
    case 'float':
      return `r.readFloat32()`;
    case 'double':
      return `r.readFloat64()`;
    case 'int64':
      return `r.readBigInt64()`;
    case 'bool':
      return `r.readBoolean()`;
    case 'bytes':
      return `r.readBytes()`;
    default:
      return `decode${field.type}(r.readBytes())`;
  }
}

export function generateTypeScript(ast: SchemaAST): string {
  const out: string[] = [];

  out.push(`// Generated by Aether-WV Compiler (aetherc). DO NOT EDIT.`);
  out.push(`import { BinaryWriter, BinaryReader, AetherClient } from 'aether-wv';\n`);

  // Messages
  for (const msg of ast.messages) {
    out.push(`export interface ${msg.name} {`);
    for (const f of msg.fields) {
      out.push(`  ${f.name}: ${mapTsType(f.type)};`);
    }
    out.push(`}\n`);

    // Encoder
    out.push(`export function encode${msg.name}(msg: ${msg.name}): Uint8Array {`);
    out.push(`  const w = new BinaryWriter();`);
    for (const f of msg.fields) {
      out.push(`  ${generateWriterCall(f, `msg.${f.name}`)}`);
    }
    out.push(`  return w.finish();`);
    out.push(`}\n`);

    // Decoder
    out.push(`export function decode${msg.name}(bytes: Uint8Array): ${msg.name} {`);
    out.push(`  const r = new BinaryReader(bytes);`);
    out.push(`  return {`);
    for (const f of msg.fields) {
      out.push(`    ${f.name}: ${generateReaderCall(f)},`);
    }
    out.push(`  };`);
    out.push(`}\n`);
  }

  // Services
  for (const s of ast.services) {
    out.push(`export class ${s.name}Client {`);
    out.push(`  constructor(private client: AetherClient, private token: string = '') {}\n`);

    for (const m of s.methods) {
      if (!m.isOutputStream) {
        // Unary RPC
        out.push(`  async ${m.name.charAt(0).toLowerCase() + m.name.slice(1)}(request: ${m.inputType}): Promise<${m.outputType}> {`);
        out.push(`    const reqBytes = encode${m.inputType}(request);`);
        out.push(`    const resBytes = await this.client.invoke('${s.name}', '${m.name}', reqBytes, this.token);`);
        out.push(`    return decode${m.outputType}(resBytes);`);
        out.push(`  }\n`);
      } else {
        // Reactive Stream
        out.push(`  async *${m.name.charAt(0).toLowerCase() + m.name.slice(1)}(request: ${m.inputType}, options?: { signal?: AbortSignal }): AsyncIterableIterator<${m.outputType}> {`);
        out.push(`    const reqBytes = encode${m.inputType}(request);`);
        out.push(`    const rawStream = this.client.stream('${s.name}', '${m.name}', reqBytes, this.token, options?.signal);`);
        out.push(`    for await (const chunk of rawStream) {`);
        out.push(`      yield decode${m.outputType}(chunk);`);
        out.push(`    }`);
        out.push(`  }\n`);
      }
    }
    out.push(`}\n`);
  }

  return out.join('\n');
}
