import { SchemaAST, FieldDefinition } from './ast.js';

function mapSwiftType(type: string): string {
  switch (type) {
    case 'string':   return 'String';
    case 'int32':    return 'Int32';
    case 'uint32':   return 'UInt32';
    case 'int64':    return 'Int64';
    case 'float':    return 'Float';
    case 'double':   return 'Double';
    case 'bool':     return 'Bool';
    case 'bytes':    return 'Data';
    default:         return type;
  }
}

function swiftWriterCall(f: FieldDefinition, accessor: string): string {
  switch (f.type) {
    case 'string':  return `w.writeString(${accessor})`;
    case 'int32':   return `w.writeInt32(${accessor})`;
    case 'uint32':  return `w.writeUInt32(${accessor})`;
    case 'int64':   return `w.writeInt64(${accessor})`;
    case 'float':   return `w.writeFloat(${accessor})`;
    case 'double':  return `w.writeDouble(${accessor})`;
    case 'bool':    return `w.writeBool(${accessor})`;
    case 'bytes':   return `w.writeBytes(${accessor})`;
    default:        return `w.writeBytes(encode${f.type}(${accessor}))`;
  }
}

function swiftReaderCall(f: FieldDefinition): string {
  switch (f.type) {
    case 'string':  return `try r.readString()`;
    case 'int32':   return `try r.readInt32()`;
    case 'uint32':  return `try r.readUInt32()`;
    case 'int64':   return `try r.readInt64()`;
    case 'float':   return `try r.readFloat()`;
    case 'double':  return `try r.readDouble()`;
    case 'bool':    return `try r.readBool()`;
    case 'bytes':   return `try r.readBytes()`;
    default:        return `try decode${f.type}(r.readBytes())`;
  }
}

export function generateSwift(ast: SchemaAST): string {
  const out: string[] = [];

  out.push(`// Generated by Aether-WV Compiler (aetherc). DO NOT EDIT.`);
  out.push(`import Foundation`);
  out.push(`import AetherWV\n`);

  // ── Messages ────────────────────────────────────────────────────────────
  for (const msg of ast.messages) {
    // Struct
    out.push(`public struct ${msg.name}: Sendable, Equatable {`);
    for (const f of msg.fields) {
      out.push(`    public var ${f.name}: ${mapSwiftType(f.type)}`);
    }
    out.push(`\n    public init(${msg.fields.map(f => `${f.name}: ${mapSwiftType(f.type)}`).join(', ')}) {`);
    for (const f of msg.fields) {
      out.push(`        self.${f.name} = ${f.name}`);
    }
    out.push(`    }`);
    out.push(`}\n`);

    // Encoder
    out.push(`public func encode${msg.name}(_ msg: ${msg.name}) -> Data {`);
    out.push(`    let w = AetherWriter()`);
    for (const f of msg.fields) {
      out.push(`    ${swiftWriterCall(f, `msg.${f.name}`)}`);
    }
    out.push(`    return w.finish()`);
    out.push(`}\n`);

    // Decoder
    out.push(`public func decode${msg.name}(_ data: Data) throws -> ${msg.name} {`);
    out.push(`    let r = AetherReader(data)`);
    out.push(`    return ${msg.name}(`);
    const decoderLines = msg.fields.map((f, i) => {
      const comma = i < msg.fields.length - 1 ? ',' : '';
      return `        ${f.name}: ${swiftReaderCall(f)}${comma}`;
    });
    out.push(...decoderLines);
    out.push(`    )`);
    out.push(`}\n`);
  }

  // ── Service Protocols ────────────────────────────────────────────────────
  for (const s of ast.services) {
    const protocolName = s.name.endsWith('Service') ? `${s.name}Protocol` : `${s.name}ServiceProtocol`;
    out.push(`public protocol ${protocolName}: Actor {`);
    for (const m of s.methods) {
      const mn = m.name.charAt(0).toLowerCase() + m.name.slice(1);
      if (!m.isOutputStream) {
        out.push(`    func ${mn}(request: ${m.inputType}) async throws -> ${m.outputType}`);
      } else {
        out.push(`    func ${mn}(request: ${m.inputType}) -> AsyncThrowingStream<${m.outputType}, Error>`);
      }
    }
    out.push(`}\n`);

    // ── Typed Client Stub ──────────────────────────────────────────────────
    const clientName = s.name.endsWith('Service') ? `${s.name}Client` : `${s.name}ServiceClient`;
    out.push(`public final class ${clientName} {`);
    out.push(`    private let client: AetherClient`);
    out.push(`    private let token: String`);
    out.push(`    public init(client: AetherClient, token: String = "") {`);
    out.push(`        self.client = client`);
    out.push(`        self.token = token`);
    out.push(`    }`);
    out.push(``);
    for (const m of s.methods) {
      const mn = m.name.charAt(0).toLowerCase() + m.name.slice(1);
      if (!m.isOutputStream) {
        out.push(`    public func ${mn}(request: ${m.inputType}) async throws -> ${m.outputType} {`);
        out.push(`        let reqData = encode${m.inputType}(request)`);
        out.push(`        let resData = try await client.invoke(service: "${s.name}", method: "${m.name}", payload: reqData, token: token)`);
        out.push(`        return try decode${m.outputType}(resData)`);
        out.push(`    }`);
      } else {
        out.push(`    public func ${mn}(request: ${m.inputType}) -> AsyncThrowingStream<${m.outputType}, Error> {`);
        out.push(`        AsyncThrowingStream { continuation in`);
        out.push(`            let reqData = encode${m.inputType}(request)`);
        out.push(`            client.stream(service: "${s.name}", method: "${m.name}", payload: reqData, token: token) { chunk, done, error in`);
        out.push(`                if let error { continuation.finish(throwing: error); return }`);
        out.push(`                if let chunk, let val = try? decode${m.outputType}(chunk) { continuation.yield(val) }`);
        out.push(`                if done { continuation.finish() }`);
        out.push(`            }`);
        out.push(`        }`);
        out.push(`    }`);
      }
      out.push(``);
    }
    out.push(`}\n`);
  }

  return out.join('\n');
}

