import { SchemaAST, FieldDefinition } from './ast.js';

function mapKotlinType(type: string): string {
  switch (type) {
    case 'string':  return 'String';
    case 'int32':   return 'Int';
    case 'uint32':  return 'UInt';
    case 'int64':   return 'Long';
    case 'float':   return 'Float';
    case 'double':  return 'Double';
    case 'bool':    return 'Boolean';
    case 'bytes':   return 'ByteArray';
    default:        return type;
  }
}

function kotlinWriterCall(f: FieldDefinition, accessor: string): string {
  switch (f.type) {
    case 'string':  return `w.writeString(${accessor})`;
    case 'int32':   return `w.writeInt(${accessor})`;
    case 'uint32':  return `w.writeUInt(${accessor})`;
    case 'int64':   return `w.writeLong(${accessor})`;
    case 'float':   return `w.writeFloat(${accessor})`;
    case 'double':  return `w.writeDouble(${accessor})`;
    case 'bool':    return `w.writeBoolean(${accessor})`;
    case 'bytes':   return `w.writeBytes(${accessor})`;
    default:        return `w.writeBytes(encode${f.type}(${accessor}))`;
  }
}

function kotlinReaderCall(f: FieldDefinition): string {
  switch (f.type) {
    case 'string':  return `r.readString()`;
    case 'int32':   return `r.readInt()`;
    case 'uint32':  return `r.readUInt()`;
    case 'int64':   return `r.readLong()`;
    case 'float':   return `r.readFloat()`;
    case 'double':  return `r.readDouble()`;
    case 'bool':    return `r.readBoolean()`;
    case 'bytes':   return `r.readBytes()`;
    default:        return `decode${f.type}(r.readBytes())`;
  }
}

export function generateKotlin(ast: SchemaAST): string {
  const out: string[] = [];

  out.push(`// Generated by Aether-WV Compiler (aetherc). DO NOT EDIT.`);
  out.push(`package ${ast.packageName}\n`);
  out.push(`import kotlinx.coroutines.flow.Flow`);
  out.push(`import kotlinx.coroutines.flow.flow`);
  out.push(`import com.aetherwv.AetherWriter`);
  out.push(`import com.aetherwv.AetherReader`);
  out.push(`import com.aetherwv.AetherClient\n`);

  // ── Messages ────────────────────────────────────────────────────────────
  for (const msg of ast.messages) {
    // Data class
    out.push(`data class ${msg.name}(`);
    for (let i = 0; i < msg.fields.length; i++) {
      const f = msg.fields[i];
      const comma = i === msg.fields.length - 1 ? '' : ',';
      out.push(`    val ${f.name}: ${mapKotlinType(f.type)}${comma}`);
    }
    out.push(`)\n`);

    // Encoder
    out.push(`fun encode${msg.name}(msg: ${msg.name}): ByteArray {`);
    out.push(`    val w = AetherWriter()`);
    for (const f of msg.fields) {
      out.push(`    ${kotlinWriterCall(f, `msg.${f.name}`)}`);
    }
    out.push(`    return w.finish()`);
    out.push(`}\n`);

    // Decoder
    out.push(`fun decode${msg.name}(bytes: ByteArray): ${msg.name} {`);
    out.push(`    val r = AetherReader(bytes)`);
    out.push(`    return ${msg.name}(`);
    for (let i = 0; i < msg.fields.length; i++) {
      const f = msg.fields[i];
      const comma = i < msg.fields.length - 1 ? ',' : '';
      out.push(`        ${f.name} = ${kotlinReaderCall(f)}${comma}`);
    }
    out.push(`    )`);
    out.push(`}\n`);
  }

  // ── Service Interfaces ───────────────────────────────────────────────────
  for (const s of ast.services) {
    const interfaceName = s.name.endsWith('Service') ? s.name : `${s.name}Service`;
    out.push(`interface ${interfaceName} {`);
    for (const m of s.methods) {
      const mn = m.name.charAt(0).toLowerCase() + m.name.slice(1);
      if (!m.isOutputStream) {
        out.push(`    suspend fun ${mn}(request: ${m.inputType}): ${m.outputType}`);
      } else {
        out.push(`    fun ${mn}(request: ${m.inputType}): Flow<${m.outputType}>`);
      }
    }
    out.push(`}\n`);

    // ── Typed Client Stub ──────────────────────────────────────────────────
    const clientName = s.name.endsWith('Service') ? `${s.name}Client` : `${s.name}ServiceClient`;
    out.push(`class ${clientName}(private val client: AetherClient, private val token: String = "") {`);
    for (const m of s.methods) {
      const mn = m.name.charAt(0).toLowerCase() + m.name.slice(1);
      if (!m.isOutputStream) {
        out.push(`    suspend fun ${mn}(request: ${m.inputType}): ${m.outputType} {`);
        out.push(`        val reqBytes = encode${m.inputType}(request)`);
        out.push(`        val resBytes = client.invoke("${s.name}", "${m.name}", reqBytes, token)`);
        out.push(`        return decode${m.outputType}(resBytes)`);
        out.push(`    }`);
      } else {
        out.push(`    fun ${mn}(request: ${m.inputType}): Flow<${m.outputType}> = flow {`);
        out.push(`        val reqBytes = encode${m.inputType}(request)`);
        out.push(`        client.stream("${s.name}", "${m.name}", reqBytes, token).collect { chunk ->`);
        out.push(`            emit(decode${m.outputType}(chunk))`);
        out.push(`        }`);
        out.push(`    }`);
      }
      out.push(``);
    }
    out.push(`}\n`);
  }

  return out.join('\n');
}

